/** Shared safe stage-2 matcher. */
const PriceFlowAvitoMatcher = (function() {
  function norm(value) { return String(value || '').trim().toLocaleLowerCase('ru-RU').replace(/ё/g, 'е'); }
  function header(value) {
    const key = norm(value).replace(/\s+/g, ' ');
    const aliases = { 'модель':'model', 'встроенная память':'memorysize', 'память':'memorysize', 'цвет':'color', 'sim конфигурация':'simconfig', 'сим конфигурация':'simconfig', 'оперативная память':'ramsize', 'озу':'ramsize', 'заголовок объявления':'title', 'наименование':'title', 'товар':'title', 'цена':'price', 'цена продажи':'price', 'актуальная цена':'price' };
    return aliases[key] || key.replace(/\s+/g, '');
  }
  function layouts(headers) {
    const prices=[]; headers.forEach(function(value,index){if(header(value)==='price')prices.push(index);});
    return prices.map(function(price,index){const start=index?prices[index-1]+1:0,block=headers.slice(start,price+1).map(header); const col=function(names){const found=names.map(function(name){return block.indexOf(name);}).find(function(i){return i>=0;});return found===undefined?-1:start+found;}; return {start:start,price:price,title:col(['title']),model:col(['model']),memory:col(['memorysize']),color:col(['color']),sim:col(['simconfig']),ram:col(['ramsize'])};});
  }
  function phoneLayout(headers) { const index={};headers.forEach(function(value,column){index[header(value)]=column;});const required=['model','memorysize','color','simconfig','ramsize','price'];return required.every(function(name){return index[name]>=0;})?{model:index.model,memory:index.memorysize,color:index.color,sim:index.simconfig,ram:index.ramsize,price:index.price}:null; }
  function titleLayout(headers) { const index={};headers.forEach(function(value,column){index[header(value)]=column;});return index.title>=0&&index.price>=0?{title:index.title,price:index.price}:null; }
  function sourceRows(headers,rows) { const result=[];layouts(headers).forEach(function(layout){rows.forEach(function(row){const price=Number(row[layout.price]),title=layout.title>=0?row[layout.title]:'',model=layout.model>=0?row[layout.model]:'';if(price>0&&(title||model))result.push({title:title,model:model,memory:layout.memory>=0?row[layout.memory]:'',color:layout.color>=0?row[layout.color]:'',sim:layout.sim>=0?row[layout.sim]:'',ram:layout.ram>=0?row[layout.ram]:'',price:price,search:row.join(' ')});});});return result; }
  function readSheet(sheet,headerRow,firstDataRow){const width=sheet.getLastColumn(),headers=sheet.getRange(headerRow,1,1,width).getValues()[0],height=Math.max(sheet.getLastRow()-firstDataRow+1,0);return{headers:headers,rows:height?sheet.getRange(firstDataRow,1,height,width).getValues():[]};}
  function writePrices(sheet,firstDataRow,column,updates){updates.sort(function(a,b){return a.row-b.row;});for(let start=0;start<updates.length;){let end=start+1;while(end<updates.length&&updates[end].row===updates[end-1].row+1)end++;sheet.getRange(firstDataRow+updates[start].row,column+1,end-start,1).setValues(updates.slice(start,end).map(function(update){return[update.price];}));start=end;}}
  function unknown(value){const text=norm(value);return !text||text==='не знаю'||text==='n/a'||text==='unknown';}
  function label(row,layout){return[row[layout.model],row[layout.memory],row[layout.color],row[layout.sim],row[layout.ram]].map(String).join(' | ');}
  // Every source field is checked so a condition marker cannot hide outside Title/Model.
  function eligible(value){return !/(?:\b(?:asis|асис|cpo|цпо|open\s*box|refurb(?:ished)?)\b|уцен|витрин|демо|пред\s*актив|предактив|вскрыт[а-я]*\s*(?:короб|упаков)|поврежд[а-я]*\s*(?:короб|упаков)|мят(?:ая|ый|ой|ую|ые|ых)?\s*(?:короб|упаков))/iu.test(String(value||''));}
  function memory(value){const found=/^(\d+(?:[.,]\d+)?)\s*(гб|gb|тб|tb)$/i.exec(String(value||'').trim());return found?String(Number(found[1].replace(',','.'))*(/тб|tb/i.test(found[2])?1024:1))+'gb':norm(value);}
  function sim(value){const text=norm(value).replace(/[\-–—]/g,' ').replace(/\s+/g,' ').trim();if(unknown(text))return'';if(/\b(?:2\s*sim|2\s*сим|dual\s*sim|sim\s*\+\s*e\s*sim)\b/.test(text))return'physical';if(/\b(?:только\s*)?e\s*sim\b/.test(text))return'esim';return text;}
  function color(value){const text=norm(value),groups=[['голуб','синий'],['blue','синий'],['ультрамарин','синий'],['teal','синий'],['black','черный'],['черн','черный'],['white','белый'],['бел','белый'],['silver','серебристый'],['сереб','серебристый'],['gold','золотистый'],['золот','золотистый'],['pink','розовый'],['розов','розовый'],['purple','фиолетовый'],['фиолет','фиолетовый'],['green','зеленый'],['зелен','зеленый'],['yellow','желтый'],['желт','желтый'],['gray','серый'],['grey','серый'],['сер','серый']],hit=groups.find(function(pair){return text.indexOf(pair[0])>=0;});return hit?hit[1]:text;}
  function phoneModel(value,options){const model=norm(value).replace(/\s+/g,' ');if(model==='galaxy s26+')return'galaxy s26 plus';if(options&&options.allowIphoneAirAlias&&model==='iphone air')return'iphone 17 air';return model;}
  function itemEligible(item){return eligible(item.search||[item.title,item.model,item.memory,item.color,item.sim,item.ram].join(' '));}
  function phoneCandidates(items,target,options){const model=phoneModel(target.model,options),targetMemory=memory(target.memory),targetColor=color(target.color),targetSim=sim(target.sim),targetRam=norm(target.ram),iphone=/^iphone\b/.test(model);if(unknown(model))return[];return items.filter(function(item){return itemEligible(item)&&phoneModel(item.model||item.title,options)===model&&(!targetMemory||memory(item.memory)===targetMemory)&&(!targetColor||color(item.color)===targetColor)&&(!targetSim||sim(item.sim)===targetSim)&&(iphone||!targetRam||norm(item.ram)===targetRam);});}
  function phoneReason(items,target,options){const ordinary=items.filter(itemEligible),byModel=ordinary.filter(function(item){return phoneModel(item.model||item.title,options)===phoneModel(target.model,options);});if(!byModel.length)return'Нет модели у поставщика';const byMemory=unknown(target.memory)?byModel:byModel.filter(function(item){return memory(item.memory)===memory(target.memory);});if(!byMemory.length)return'Нет нужной памяти';const byColor=unknown(target.color)?byMemory:byMemory.filter(function(item){return color(item.color)===color(target.color);});if(!byColor.length)return'Нет нужного цвета';const bySim=unknown(target.sim)?byColor:byColor.filter(function(item){return sim(item.sim)===sim(target.sim);});if(!bySim.length)return'Нет нужной SIM';const byRam=/^iphone\b/.test(phoneModel(target.model,options))||unknown(target.ram)?bySim:bySim.filter(function(item){return norm(item.ram)===norm(target.ram);});return byRam.length?'Нет точного SKU у поставщика':'Нет нужной RAM';}
  function cheapestPhone(items,target,options){const candidates=phoneCandidates(items,target,options),prices=candidates.map(function(item){return Number(item.price);}).filter(Boolean);return prices.length?{price:Math.min.apply(null,prices),candidates:candidates}:null;}
  function planPhone(source,layout,rows,options){const updates=[],missing=[],reasons=[];let matched=0,cleared=0;rows.forEach(function(row,index){const target={model:row[layout.model],memory:row[layout.memory],color:row[layout.color],sim:row[layout.sim],ram:layout.ram>=0?row[layout.ram]:''};if(unknown(target.model)){reasons[index]='';return;}const candidate=cheapestPhone(source,target,options);if(!candidate){const reason=phoneReason(source,target,options);reasons[index]=reason;missing.push(reason);if(row[layout.price]!==''){updates.push({row:index,price:''});cleared++;}return;}matched++;reasons[index]='';if(Number(row[layout.price])!==candidate.price)updates.push({row:index,price:candidate.price});});return{updates:updates,matched:matched,cleared:cleared,missing:missing,reasons:reasons,ambiguous:[]};}
  function words(value){const ignored={apple:true,samsung:true,sony:true,новый:true,актив:true,active:true,wifi:true,unknown:true,не:true,знаю:true};const text=norm(value).replace(/ipad\s+(\d+)\s+mini/g,'ipad mini $1').replace(/(?:apple\s+)?watch\s+(?:series\s+)?(se|ultra)\s+(\d+)/g,'watch $1$2').replace(/(?:apple\s+)?watch\s+series\s+(\d+)/g,'watch s$1').replace(/playstation/g,'ps').replace(/\bps\s+(\d)\b/g,'ps$1').replace(/airpods\s+max\s+(?:2\s+)?2026\b/g,'airpodsmax2026').replace(/airpods\s+pro\s+(\d+)/g,'airpods pro$1').replace(/airpods\s+(\d+)/g,'airpods$1').replace(/\b([hsdt])\s*(\d{2})\b/g,'$1$2').replace(/(\d+)\s*\/\s*(\d+)(?:\s*(gb|гб|tb|тб))?/g,function(_,ram,storage,unit){const n=Number(storage);return ram+'x'+(n===1024?'1':n===2048?'2':storage)+(/tb|тб/i.test(unit||'')||n===1024||n===2048?'tb':'gb');}).replace(/(\d+)\s*(?:gb|гб)/g,'$1gb').replace(/(\d+)\s*(?:tb|тб)/g,'$1tb').replace(/[()\[\],.;:+/\\-]+/g,' ').replace(/\s+/g,' ').trim();return Array.from(new Set(text.split(' ').filter(function(word){return word&&!ignored[word]&&!/^\d{4}$/.test(word);})));}
  function macbookKey(value){const text=norm(value),family=/macbook\s+(?:\d+\s+)?neo\b/.test(text)?'neo':/macbook\s+air\b/.test(text)?'air':/macbook\s+pro\b/.test(text)?'pro':'',chip=/\bm\s*(\d+)\b/i.exec(text),screen=/\b(13|14|15|16)\s*(?:[″”\"]|inch|дюйм)?\b/.exec(text),config=/(8|16|24|32|36|48|64)\s*(?:\/|gb\s*\/|гб\s*\/|gb\s+|гб\s+)(256|512|1024|2048|1|2)\s*(gb|гб|tb|тб)?\b/i.exec(text);if(!family||(!chip&&family!=='neo')||!config||(family!=='neo'&&!screen))return'';const n=Number(config[2]),storage=(n===1024?'1':n===2048?'2':config[2])+((/tb|тб/i.test(config[3]||'')||n===1024||n===2048)?'tb':'gb');return[family,family==='neo'?'':screen[1],chip?'m'+chip[1]:'',config[1]+'x'+storage].join('|');}
  function dysonKey(value){const text=norm(value);if(/\bon\s*trac\b/.test(text))return'ontrac';const found=/\b(hs|hd|ht)\s*(\d{2})\b/i.exec(text);return found?found[1].toLowerCase()+found[2]:'';}
  function playstation(value){const text=norm(value).replace(/playstation/g,'ps');if(/dual\s*sense/.test(text))return{family:/charg|dock|stand|station|заряд|док|подстав/.test(text)?'accessory':'dualsense',edge:/\bedge\b/.test(text)};const gen=/\bps\s*([345])\b/.exec(text);if(!gen)return null;const mem=/\b(825|1000|1024|2000|2048)\s*(?:gb|гб)|\b([12])\s*(?:tb|тб)\b/i.exec(text);return{family:'ps'+gen[1],form:/\bpro\b/.test(text)?'pro':/\bslim\b/.test(text)?'slim':'standard',media:/\bdigital\b/.test(text)?'digital':/\b(?:disc|disk|diskdrive)\b|диск/.test(text)?'disc':'',memory:mem?Number(mem[1]||Number(mem[2])*1024):0};}
  function iPadMiniGeneration(value){const text=norm(value).replace(/\bipad\s+(\d+)\s+mini\b/g,'ipad mini $1'),found=/\bipad\s+mini\s+(\d+)\b/.exec(text);return found?found[1]:'';}
  function titleMatches(category,target,candidate){const a=words(target),b=words(candidate),has=function(word){return b.indexOf(word)>=0;};if(!a.length||!b.length)return false;if(category==='макбуки'){const key=macbookKey(target);return Boolean(key&&key===macbookKey(candidate));}if(category==='дайсон'){const key=dysonKey(target);return Boolean(key&&key!=='ontrac'&&key===dysonKey(candidate));}if(category==='пс'){const left=playstation(target),right=playstation(candidate);if(!left||!right||left.family!==right.family||right.family==='accessory')return false;if(left.family==='dualsense')return left.edge===right.edge;if(left.form==='standard'&&!left.media&&!left.memory)return right.form==='standard';if(left.form==='slim'&&!left.media&&!left.memory)return right.form==='slim';return left.form===right.form&&(!left.media||right.media===left.media)&&(!left.memory||left.memory===right.memory);}if(category==='айпады'){const targetMini=iPadMiniGeneration(target),candidateMini=iPadMiniGeneration(candidate);if(targetMini||candidateMini){if(!targetMini||!candidateMini||targetMini!==candidateMini)return false;}}if(category==='наушники'){const onTrac=/\bon\s*trac\b/i.test(target);if(onTrac)return/\bon\s*trac\b/i.test(candidate);if(/\bon\s*trac\b/i.test(candidate))return false;const max2026=/airpods\s+max\s+(?:2\s+)?2026/i.test(target);if(max2026)return/airpods\s+max\s+(?:2\s+)?2026/i.test(candidate);if(/\banc\b|шумоподав/i.test(target)!==/\banc\b|шумоподав/i.test(candidate))return false;}const required=category==='айпады'?/^(?:ipad|air|pro|mini|(?:m|a)\d+|\d+(?:gb|tb)|\d+|nano|texture)$/:category==='часы'?/^(?:watch|(?:se|ultra|s)\d+)$/:category==='наушники'?/^(?:airpods\d+|airpodsmax2026|pro\d+)$/:/./;const selected=a.filter(function(word){return required.test(word);});return selected.length>0&&selected.every(has);}
  function cheapestTitle(items,category,target){const candidates=items.filter(function(item){return itemEligible(item)&&titleMatches(category,target,item.title);}),prices=candidates.map(function(item){return Number(item.price);}).filter(Boolean);return prices.length?{price:Math.min.apply(null,prices),candidates:candidates}:null;}
  function titleFamily(category,value){const text=norm(value);if(category==='макбуки')return /macbook\s+(?:\d+\s+)?neo\b/.test(text)?'neo':/macbook\s+air\b/.test(text)?'air':/macbook\s+pro\b/.test(text)?'pro':'';if(category==='дайсон')return dysonKey(text);if(category==='пс'){const product=playstation(text);return product?product.family+(product.form||''):'';}if(category==='наушники'){const onTrac=/\bon\s*trac\b/.test(text);const airpods=/\bairpods\s*(?:pro\s*)?(\d+|max)?/i.exec(text);return onTrac?'ontrac':airpods?'airpods '+(airpods[1]||''):'';}if(category==='айпады'){const model=/\bipad\s+(mini|air|pro)?/i.exec(text);return model?'ipad '+(model[1]||'base'):'';}if(category==='часы'){const watch=/\b(?:apple\s+)?watch\s+(?:series\s+)?(se|ultra|\d+)/i.exec(text);return watch?'watch '+watch[1]:'';}return '';}
  function titleReason(items,category,title){if(!String(title||'').trim())return'';const family=titleFamily(category,title);if(!family)return'Нет точного SKU у поставщика';const hasFamily=items.some(function(item){return itemEligible(item)&&titleFamily(category,item.title)===family;});return hasFamily?'Нет точного SKU у поставщика':'Нет модели у поставщика';}
  function planTitle(source,category,layout,rows){const updates=[],missing=[],reasons=[],ambiguous=[];let matched=0,cleared=0;rows.forEach(function(row,index){const title=row[layout.title],candidate=cheapestTitle(source,category,title);if(!candidate){const reason=titleReason(source,category,title);reasons[index]=reason;if(reason)missing.push(reason);if(row[layout.price]!==''){updates.push({row:index,price:''});cleared++;}return;}matched++;reasons[index]='';if((category==='макбуки'||category==='пс')&&candidate.candidates.length>1)ambiguous.push({row:index,title:String(title),prices:candidate.candidates.map(function(item){return item.price;}).sort(function(a,b){return a-b;})});if(Number(row[layout.price])!==candidate.price)updates.push({row:index,price:candidate.price});});return{updates:updates,matched:matched,cleared:cleared,missing:missing,reasons:reasons,ambiguous:ambiguous};}
  function sync(config){if(!config||!config.sourceSpreadsheet||!config.avitoSpreadsheetId||!config.sheets)throw new Error('PriceFlowAvitoMatcher: неполная конфигурация.');const sourceBook=config.sourceSpreadsheet,avitoBook=SpreadsheetApp.openById(config.avitoSpreadsheetId),sourceHeaderRow=config.sourceHeaderRow||1,sourceFirstDataRow=config.sourceFirstDataRow||sourceHeaderRow+1,headerRow=config.headerRow||2,firstDataRow=config.firstDataRow||headerRow+1,staged=[],report={at:new Date().toISOString(),city:config.city||'',sourceRows:0,sheets:{}};Object.keys(config.sheets).forEach(function(category){const target=config.sheets[category],sourceSheet=sourceBook.getSheetByName(category),avitoSheet=avitoBook.getSheets().find(function(sheet){return sheet.getSheetId()===target.sheetId;});if(!sourceSheet||!avitoSheet)throw new Error('PriceFlowAvitoMatcher: отсутствует лист «'+category+'».');const source=readSheet(sourceSheet,sourceHeaderRow,sourceFirstDataRow),destination=readSheet(avitoSheet,headerRow,firstDataRow),sourceItems=sourceRows(source.headers,source.rows),layout=target.kind==='phone'?phoneLayout(destination.headers):titleLayout(destination.headers);if(!layout||!layouts(source.headers).length)throw new Error('PriceFlowAvitoMatcher: неверная шапка «'+(!layout?avitoSheet.getName():sourceSheet.getName())+'»; запись не выполнена.');const plan=target.kind==='phone'?planPhone(sourceItems,layout,destination.rows,config):planTitle(sourceItems,category,layout,destination.rows);staged.push({sheet:avitoSheet,price:layout.price,plan:plan});report.sourceRows+=sourceItems.length;report.sheets[category]={matched:plan.matched,updated:plan.updates.length,cleared:plan.cleared,missing:plan.missing.slice(0,200),ambiguous:plan.ambiguous};});staged.forEach(function(item){writePrices(item.sheet,firstDataRow,item.price,item.plan.updates);});return report;}
  function runRegressionTests(){const failures=[],ok=function(value,name){if(!value)failures.push(name);};ok(sim('2 SIM')===sim('SIM + eSIM'),'2 SIM / SIM + eSIM');ok(sim('eSIM')!==sim('2 SIM'),'eSIM isolation');ok(!eligible('iPhone 16 Pro CPO'),'special condition');ok(!eligible('iPhone 16 Pro|open box'),'all source fields condition');ok(phoneModel('Galaxy S26+')===phoneModel('Galaxy S26 Plus'),'Galaxy S26+ alias');ok(phoneModel('iPhone Air')!==phoneModel('iPhone 17 Air'),'unapproved iPhone Air alias');ok(titleMatches('макбуки','MacBook Air 13 M5 16/512','MacBook Air 13 M5 16/512'),'MacBook');ok(!titleMatches('макбуки','MacBook Air 13 M5 16/512','MacBook Air 15 M5 16/512'),'MacBook screen');ok(titleMatches('дайсон','Dyson HS08 Blue','Dyson HS08 Red'),'Dyson code');ok(titleMatches('пс','PS5 Slim','PS5 Slim Digital 825 GB'),'PS5 Slim fallback');ok(!titleMatches('пс','PS5','PS5 Slim Digital 825 GB'),'PS5 standard isolation');ok(!titleMatches('пс','DualSense','DualSense Edge'),'DualSense isolation');ok(titleMatches('наушники','Dyson OnTrac','Dyson OnTrac CNC Black'),'OnTrac');ok(!titleMatches('наушники','Dyson OnTrac','AirPods Pro 3'),'OnTrac isolation');ok(titleMatches('айпады','iPad 7 mini (2024) 256 GB Wi-Fi Blue','iPad Mini 7 A17 256 GB Wi-Fi Blue'),'iPad mini 7');ok(!titleMatches('айпады','iPad 7 mini (2024) 256 GB Wi-Fi Blue','iPad Mini 6 256 GB Wi-Fi Blue'),'iPad mini generation');if(failures.length)throw new Error('PriceFlow matcher regression: '+failures.join(', '));return{passed:17};}
  return {sync:sync,planPhone:planPhone,planTitle:planTitle,phoneLayout:phoneLayout,titleLayout:titleLayout,sourceRows:sourceRows,header:header,sim:sim,eligible:eligible,phoneModel:phoneModel,phoneCandidates:phoneCandidates,titleMatches:titleMatches,runRegressionTests:runRegressionTests};
})();
